python:
  - artifactory.devhub-cloud.cisco.com/python:3.12
  - containers.cisco.com/sto-ccc-cloud9/python:3.12
node:
  - artifactory.devhub-cloud.cisco.com/node:20
  - containers.cisco.com/sto-ccc-cloud9/node:20
golang:
  - artifactory.devhub-cloud.cisco.com/golang:1.21
  - containers.cisco.com/sto-ccc-cloud9/golang:1.21
